### ISSUE TITLE
Parallel execution seems not to be working

### ISSUE THREAD

**Issue by sherrberger** [sapcc/swift-http-import#13]
Hello,

we did some long running tests with the tool and it looks like that the workers section is not used.
The amount of copied data was the same with and without the workers section.
Is there somehow a way to check, if parallel threads are used?

Our version: 1.1

**Comment by reimannf** [comment]
Would you mind to paste your config file, of cause without the sensitive data?

**Comment by sherrberger** [comment]
Which kind of information is needed in detail? We have the sections swift, jobs and workers.

**Comment by reimannf** [comment]
The whole yaml file, without passwords, concrete urls and so on.

**Comment by reimannf** [comment]
Additionally, you might want to run swift-http-import in debug mode: 
`DEBUG=1 swift-http-import config.yaml`

**Comment by majewsky** [comment]
@sherrberger I heard that you resolved this in direct discussion with @reimannf? If so, can we close this?

**Comment by reimannf** [comment]
Yes. The post mortem discussion let me think it was a combination of two things:
- Too many transfer workers (500) for the target swift, which leads to rate limits (50 PUTS/s)
- Too many really small files on the target, which adds more overhead than needed to the transfer
Unfortunately the environment is not available any longer, so this is the best analysis we can get.
