### ISSUE TITLE
add option: do not store plain-text passwords in config file

### ISSUE THREAD

**Issue by majewsky** [sapcc/swift-http-import#28]
Offer to read passwords from environment variables instead.

**Comment by kayrus** [comment]
I suggest switching to `github.com/gophercloud/utils/openstack/clientconfig` package.

**Comment by majewsky** [comment]
We need to sync between multiple Swift clusters, so `OS_PASSWORD` is not enough.

**Comment by kayrus** [comment]
Can the [envPrefix](https://github.com/gophercloud/utils/blob/fbb6ab446f0167dfa4d25b8eb0c0d2f873924516/openstack/clientconfig/requests.go#L425) option solve this case?
