### ISSUE TITLE
sks-keyservers.net has been discontinued

### ISSUE THREAD

**Issue by majewsky** [sapcc/swift-http-import#49]
When verifying GPG signatures in Yum and Debian repos, s-h-i always pulls the respective GPG keys from the SKS pool. However, SKS has discontinued their service effective immediately (see attached screenshot).

For our own internal repo sync, this currently affects the Ubuntu and Suse repos. To keep the sync jobs alive for now, I've set `verify_signature: false` on them. But of course, the verification is desirable, so we need to figure out where to pull keys from instead. We should check with the distributions' documentations to find out where we can retrieve GPG keys from instead. (Maybe they are distributed with the repos? Or the distros have their own key pools somewhere?)

---

![image](https://user-images.githubusercontent.com/24696/123239888-18df9200-d4e0-11eb-823d-a80343319cea.png)

**Comment by majewsky** [comment]
We can switch from `pool.sks-keyservers.net` to `pgp.mit.edu`. It runs [the same software](https://github.com/SKS-Keyserver/sks-keyserver) and thus can be queried in the same way. We should make the keyserver URL configurable though to make future switches less painful.

**Comment by majewsky** [comment]
@talal I made a half-baked fix to move to `pgp.mit.edu` and provide some configurability for keyserver URLs going forward. This change is enough to reenable signature verification on our repo sync, but there is still some polish to apply. I opened #50 for that, please take care of that after #48.

**Comment by talal** [comment]
@majewsky Will do. Thanks for the fix!
